name: deploy-container

on: 
  push:
    branches:
      - master
    paths:
      - 'container/**'  

defaults: 
  run:
    working-directory: container

jobs: 
  build:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://microfrontend-dashboard1/container/latest --endpoint-url=https://s3.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1